services:
  floci:
    image: floci/floci
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb,sqs
    profiles: ["sim"]

  order-service:
    build:
      context: .
      dockerfile: services/order-service/Dockerfile
    profiles: ["sim"]
    depends_on: [floci]
    environment:
      - OTEL_SERVICE_NAME=order-service
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-lgtm:4318
      - AWS_ENDPOINT_URL=http://floci:4566
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test

  worker-service:
    build:
      context: .
      dockerfile: services/worker-service/Dockerfile
    profiles: ["sim"]
    depends_on: [floci]
    environment:
      - OTEL_SERVICE_NAME=worker-service
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-lgtm:4318
      - AWS_ENDPOINT_URL=http://floci:4566
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    profiles: ["sim"]
    depends_on:
      - order-service

  otel-lgtm:
    image: grafana/otel-lgtm
    profiles: ["obs"]
    ports: ["3000:3000", "4317:4317", "4318:4318"]
