log_format incidentlab '$remote_addr - [$time_local] "$request" '
                        '$status $body_bytes_sent rt=$request_time '
                        'uct="$upstream_connect_time" urt="$upstream_response_time"';

server {
    listen 80;
    access_log /var/log/nginx/access.log incidentlab;

    location /orders {
        proxy_pass http://order-service:3001;
    }

    location /admin/ {
        proxy_pass http://order-service:3001;
    }
}
